[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "forge-std=lib/forge-std/src",
  "solady=lib/solady/src",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "aerodrome-finance/contracts/=lib/aerodrome-finance/contracts/",
  "aerodrome-slipstream/contracts/=lib/aerodrome-slipstream/contracts/",
  "lib/aerodrome-slipstream:contracts/=lib/aerodrome-slipstream/contracts/"
]
# tenderly
cbor_metadata = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${SEPOLIA_ETHERSCAN_API_KEY}", url = "${SEPOLIA_ETHERSCAN_VERIFIER_URL}" }

